# Generated by Django 4.2.16 on 2024-11-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_colecao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colecao",
            options={"ordering": ("nome",)},
        ),
    ]
